/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness and dependency check: database and Redis.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Data freshness for the banner: the latest sale in the register and what is provisional.
         */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Properties
         * @description The list view synced with the map: the latest matching sale per property in the box.
         */
        get: operations["list_properties_api_v1_properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Property Detail
         * @description The property page: every sale, location precision, areas, vicinity and area trend.
         */
        get: operations["property_detail_api_v1_properties__property_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description The hover card: one precomputed row, cached in Redis per data version.
         */
        get: operations["summary_api_v1_properties__property_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AreaLine */
        AreaLine: {
            /** Change12Mpct */
            change12mPct?: number | null;
            /** Kind */
            kind: string;
            /** Median12M */
            median12m?: number | null;
            /** N */
            n: number;
            /** Name */
            name: string;
            /** Provisional */
            provisional: boolean;
        };
        /** AreaRef */
        AreaRef: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** AreaSeries */
        AreaSeries: {
            area: components["schemas"]["AreaRef"];
            /**
             * Periodkind
             * @default rolling_12m
             * @constant
             */
            periodKind: "rolling_12m";
            /** Points */
            points: components["schemas"]["StatsPoint"][];
        };
        /** Flood */
        Flood: {
            /** Link */
            link: string;
            /** Note */
            note: string;
        };
        /**
         * GeocodeConfidence
         * @description Ordered from most to least precise (D-003).
         * @enum {string}
         */
        GeocodeConfidence: "exact" | "street" | "locality" | "routing_key" | "county" | "unmatched";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "error";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /** LatestSale */
        LatestSale: {
            /**
             * Date
             * Format: date
             */
            date: string;
            flags: components["schemas"]["SaleFlags"];
            /** Isnew */
            isNew: boolean;
            /** Priceeur */
            priceEur: number;
        };
        /** Location */
        Location: {
            confidence: components["schemas"]["GeocodeConfidence"];
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Method */
            method: string | null;
            /** Source */
            source: string | null;
        };
        /** Meta */
        Meta: {
            /** Dataversion */
            dataVersion: string;
            /** Lastingestat */
            lastIngestAt: string | null;
            /**
             * Pprmaxsaledate
             * Format: date
             */
            pprMaxSaleDate: string;
            /**
             * Provisionalfrom
             * Format: date
             * @description Sales on or after this date are provisional.
             */
            provisionalFrom: string;
        };
        /**
         * PoiType
         * @enum {string}
         */
        PoiType: "school_primary" | "school_post_primary" | "school_special" | "bus_stop" | "luas_stop" | "rail_station" | "dart_station" | "shop" | "supermarket" | "pharmacy" | "park" | "gym" | "restaurant" | "gp";
        /** PropertyDetail */
        PropertyDetail: {
            /** Address */
            address: string;
            areaSeries: components["schemas"]["AreaSeries"] | null;
            /** Areas */
            areas: components["schemas"]["AreaRef"][];
            /** Caveats */
            caveats: string[];
            /** County */
            county: string;
            /** Dataversion */
            dataVersion: string;
            /** Dublindistrict */
            dublinDistrict: string | null;
            /** Id */
            id: string;
            location: components["schemas"]["Location"];
            /** Routingkey */
            routingKey: string | null;
            /** Sales */
            sales: components["schemas"]["Sale"][];
            vicinity: components["schemas"]["Vicinity"];
        };
        /** PropertyList */
        PropertyList: {
            /** Items */
            items: components["schemas"]["PropertyListItem"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** PropertyListItem */
        PropertyListItem: {
            /** Address */
            address: string;
            confidence: components["schemas"]["GeocodeConfidence"];
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            latestSale: components["schemas"]["LatestSale"];
            /** Lng */
            lng: number;
            /** Nsales */
            nSales: number;
        };
        /** PropertySummary */
        PropertySummary: {
            /** Address */
            address: string;
            area?: components["schemas"]["AreaLine"] | null;
            confidence: components["schemas"]["GeocodeConfidence"];
            /** Dataversion */
            dataVersion: string;
            /** Id */
            id: string;
            latestSale?: components["schemas"]["LatestSale"] | null;
            /** Previoussales */
            previousSales?: components["schemas"]["SaleBrief"][];
            vicinity: components["schemas"]["Vicinity"];
        };
        /** Sale */
        Sale: {
            /** Bulkgroupsize */
            bulkGroupSize: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Isnew */
            isNew: boolean;
            /** Notfullmarketprice */
            notFullMarketPrice: boolean;
            /** Possibleduplicate */
            possibleDuplicate: boolean;
            /** Priceeur */
            priceEur: number;
            /** Sizeband */
            sizeBand: string | null;
            /** Vatexclusive */
            vatExclusive: boolean;
        };
        /** SaleBrief */
        SaleBrief: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Priceeur */
            priceEur: number;
        };
        /** SaleFlags */
        SaleFlags: {
            /** Bulk */
            bulk: boolean;
            /** Notfullmarketprice */
            notFullMarketPrice: boolean;
            /** Vatexclusive */
            vatExclusive: boolean;
        };
        /** SchoolValue */
        SchoolValue: {
            /** Distancem */
            distanceM: number;
            /** Name */
            name?: string | null;
        };
        /** Sourced[SchoolValue] */
        Sourced_SchoolValue_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            value: components["schemas"]["SchoolValue"];
        };
        /** Sourced[StopValue] */
        Sourced_StopValue_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            value: components["schemas"]["StopValue"];
        };
        /** Sourced[int] */
        Sourced_int_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            /** Value */
            value: number;
        };
        /** Sourced[str] */
        Sourced_str_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            /** Value */
            value: string;
        };
        /** StatsPoint */
        StatsPoint: {
            /** Median */
            median: number | null;
            /** N */
            n: number;
            /**
             * Periodstart
             * Format: date
             */
            periodStart: string;
            /** Provisional */
            provisional: boolean;
            /** Suppressed */
            suppressed: boolean;
        };
        /** StopValue */
        StopValue: {
            /** Distancem */
            distanceM: number;
            /** Name */
            name?: string | null;
            type: components["schemas"]["PoiType"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vicinity */
        Vicinity: {
            deprivation?: components["schemas"]["Sourced_str_"] | null;
            /** Distances */
            distances?: "straight line" | null;
            flood: components["schemas"]["Flood"];
            nearestPostPrimarySchool?: components["schemas"]["Sourced_SchoolValue_"] | null;
            nearestPrimarySchool?: components["schemas"]["Sourced_SchoolValue_"] | null;
            nearestStop?: components["schemas"]["Sourced_StopValue_"] | null;
            shopsWithin1km?: components["schemas"]["Sourced_int_"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    list_properties_api_v1_properties_get: {
        parameters: {
            query: {
                /** @description west,south,east,north in degrees */
                bbox: string;
                sort?: "-date" | "date" | "-price" | "price";
                page?: number;
                pageSize?: number;
                priceMin?: number | string | null;
                priceMax?: number | string | null;
                dateFrom?: string | null;
                dateTo?: string | null;
                type?: "new" | "second_hand" | "any";
                excludeNonMarket?: boolean;
                excludeBulk?: boolean;
                minConfidence?: components["schemas"]["GeocodeConfidence"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyList"];
                };
            };
            /** @description The box is too large: zoom in */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    property_detail_api_v1_properties__property_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_properties__property_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
