/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Sign out. Succeeds, and clears the cookie, even if the session had already ended.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Policies
         * @description The versions of the terms and privacy policy that registration accepts.
         */
        get: operations["policies_api_v1_auth_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account and email a verification link. Always 202.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_api_v1_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness and dependency check: database and Redis.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Close the account now; its data is purged after 30 days (`app.cli purge-deleted`).
         */
        delete: operations["delete_me_api_v1_me_delete"];
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Me
         * @description Everything stored about the account, as a JSON download (GDPR access request).
         */
        get: operations["export_me_api_v1_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/history/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Views */
        get: operations["views_api_v1_me_history_views_get"];
        put?: never;
        /**
         * Record View
         * @description Record a property page visit, unless history is switched off (then nothing is kept).
         */
        post: operations["record_view_api_v1_me_history_views_post"];
        /** Clear Views */
        delete: operations["clear_views_api_v1_me_history_views_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/history/views/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete View */
        delete: operations["delete_view_api_v1_me_history_views__view_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change the password; every other session is signed out and reset links stop working.
         */
        post: operations["change_password_api_v1_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wishlist */
        get: operations["wishlist_api_v1_me_wishlist_get"];
        put?: never;
        /**
         * Add To Wishlist
         * @description Save a property or an area (201). Saving the same one again returns the existing item
         *     (200), with its note replaced if a new one is given.
         */
        post: operations["add_to_wishlist_api_v1_me_wishlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wishlist/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare
         * @description Side by side: the hover summaries of up to four saved properties, in the order given.
         */
        get: operations["compare_api_v1_me_wishlist_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wishlist/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Wishlist Item */
        delete: operations["remove_wishlist_item_api_v1_me_wishlist__item_id__delete"];
        options?: never;
        head?: never;
        /** Note Wishlist Item */
        patch: operations["note_wishlist_item_api_v1_me_wishlist__item_id__patch"];
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Data freshness for the banner: the latest sale in the register and what is provisional.
         */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Properties
         * @description The list view synced with the map: the latest matching sale per property in the box.
         */
        get: operations["list_properties_api_v1_properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Property Detail
         * @description The property page: every sale, location precision, areas, vicinity and area trend.
         */
        get: operations["property_detail_api_v1_properties__property_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description The hover card: one precomputed row, cached in Redis per data version.
         */
        get: operations["summary_api_v1_properties__property_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Sales per month nationally, and each county's latest complete 12 months.
         */
        get: operations["overview_api_v1_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Accepted
         * @description 202 answers never say whether an account exists.
         */
        Accepted: {
            /** Message */
            message: string;
            /**
             * Status
             * @default accepted
             * @constant
             */
            status: "accepted";
        };
        /** AreaLine */
        AreaLine: {
            /** Change12Mpct */
            change12mPct?: number | null;
            /** Kind */
            kind: string;
            /** Median12M */
            median12m?: number | null;
            /** N */
            n: number;
            /** Name */
            name: string;
            /** Provisional */
            provisional: boolean;
        };
        /** AreaRef */
        AreaRef: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** AreaSeries */
        AreaSeries: {
            area: components["schemas"]["AreaRef"];
            /**
             * Periodkind
             * @default rolling_12m
             * @constant
             */
            periodKind: "rolling_12m";
            /** Points */
            points: components["schemas"]["StatsPoint"][];
        };
        /**
         * County
         * @enum {string}
         */
        County: "carlow" | "cavan" | "clare" | "cork" | "donegal" | "dublin" | "galway" | "kerry" | "kildare" | "kilkenny" | "laois" | "leitrim" | "limerick" | "longford" | "louth" | "mayo" | "meath" | "monaghan" | "offaly" | "roscommon" | "sligo" | "tipperary" | "waterford" | "westmeath" | "wexford" | "wicklow";
        /** CountyStat */
        CountyStat: {
            /**
             * Lat
             * @description A point inside the county, for centring the map.
             */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Medianpriceeur
             * @description None when fewer than 5 sales.
             */
            medianPriceEur: number | null;
            /** Name */
            name: string;
            /**
             * Sales
             * @description Market sales in the 12 months to `Overview.windowEnd`.
             */
            sales: number;
            /** Slug */
            slug: string;
        };
        /** EmailIn */
        EmailIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Flood */
        Flood: {
            /** Link */
            link: string;
            /** Note */
            note: string;
        };
        /**
         * GeocodeConfidence
         * @description Ordered from most to least precise (D-003).
         * @enum {string}
         */
        GeocodeConfidence: "exact" | "street" | "locality" | "routing_key" | "county" | "unmatched";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "error";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /** LatestSale */
        LatestSale: {
            /**
             * Date
             * Format: date
             */
            date: string;
            flags: components["schemas"]["SaleFlags"];
            /** Isnew */
            isNew: boolean;
            /** Priceeur */
            priceEur: number;
        };
        /** Location */
        Location: {
            confidence: components["schemas"]["GeocodeConfidence"];
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Method */
            method: string | null;
            /** Source */
            source: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Me */
        Me: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Email */
            email: string;
            /** Emailverified */
            emailVerified: boolean;
            /** Fullname */
            fullName: string;
            /** Historyenabled */
            historyEnabled: boolean;
            /** Id */
            id: string;
            /** Marketingoptin */
            marketingOptIn: boolean;
            /** Permissions */
            permissions: string[];
            profile: components["schemas"]["Profile-Output"];
            /** Roles */
            roles: string[];
        };
        /**
         * MePatch
         * @description Only the fields sent are changed; within `profile`, too.
         */
        MePatch: {
            /** Fullname */
            fullName?: string | null;
            /** Historyenabled */
            historyEnabled?: boolean | null;
            /** Marketingoptin */
            marketingOptIn?: boolean | null;
            profile?: components["schemas"]["Profile-Input"] | null;
        };
        /** Meta */
        Meta: {
            /** Dataversion */
            dataVersion: string;
            /** Lastingestat */
            lastIngestAt: string | null;
            /**
             * Pprmaxsaledate
             * Format: date
             */
            pprMaxSaleDate: string;
            /**
             * Provisionalfrom
             * Format: date
             * @description Sales on or after this date are provisional.
             */
            provisionalFrom: string;
        };
        /** MonthCount */
        MonthCount: {
            /**
             * Month
             * Format: date
             * @description First day of the month.
             */
            month: string;
            /**
             * Provisional
             * @description Late filings still arrive for this month.
             */
            provisional: boolean;
            /**
             * Sales
             * @description Market sales filed for this month, all counties.
             */
            sales: number;
        };
        /** Overview */
        Overview: {
            /**
             * Counties
             * @description Most sales first.
             */
            counties: components["schemas"]["CountyStat"][];
            /** Dataversion */
            dataVersion: string;
            /**
             * Firstsaledate
             * Format: date
             */
            firstSaleDate: string;
            /**
             * Monthly
             * @description The last 24 months, oldest first.
             */
            monthly: components["schemas"]["MonthCount"][];
            /** Totalproperties */
            totalProperties: number;
            /**
             * Totalsales
             * @description Every sale on the register, market or not.
             */
            totalSales: number;
            /**
             * Windowend
             * Format: date
             * @description Last month of that window: the latest complete one.
             */
            windowEnd: string;
            /**
             * Windowstart
             * Format: date
             * @description First month of the counties' 12-month window.
             */
            windowStart: string;
        };
        /** PasswordChangeIn */
        PasswordChangeIn: {
            /** Currentpassword */
            currentPassword: string;
            /** Newpassword */
            newPassword: string;
        };
        /** PasswordIn */
        PasswordIn: {
            /** Password */
            password: string;
        };
        /**
         * PoiType
         * @enum {string}
         */
        PoiType: "school_primary" | "school_post_primary" | "school_special" | "bus_stop" | "luas_stop" | "rail_station" | "dart_station" | "shop" | "supermarket" | "pharmacy" | "park" | "gym" | "restaurant" | "gp";
        /** Policies */
        Policies: {
            /** Privacyversion */
            privacyVersion: string;
            /** Termsversion */
            termsVersion: string;
        };
        /** Profile */
        "Profile-Input": {
            /** Budgetmax */
            budgetMax?: number | string | null;
            /** Budgetmin */
            budgetMin?: number | string | null;
            /** Counties */
            counties?: components["schemas"]["County"][] | null;
            propertyInterest?: components["schemas"]["PropertyInterest"] | null;
            userType?: components["schemas"]["UserType"] | null;
        };
        /** Profile */
        "Profile-Output": {
            /** Budgetmax */
            budgetMax?: number | null;
            /** Budgetmin */
            budgetMin?: number | null;
            /** Counties */
            counties?: components["schemas"]["County"][] | null;
            propertyInterest?: components["schemas"]["PropertyInterest"] | null;
            userType?: components["schemas"]["UserType"] | null;
        };
        /** PropertyDetail */
        PropertyDetail: {
            /** Address */
            address: string;
            areaSeries: components["schemas"]["AreaSeries"] | null;
            /** Areas */
            areas: components["schemas"]["AreaRef"][];
            /** Caveats */
            caveats: string[];
            /** County */
            county: string;
            /** Dataversion */
            dataVersion: string;
            /** Dublindistrict */
            dublinDistrict: string | null;
            /** Id */
            id: string;
            location: components["schemas"]["Location"];
            /** Routingkey */
            routingKey: string | null;
            /** Sales */
            sales: components["schemas"]["Sale"][];
            vicinity: components["schemas"]["Vicinity"];
        };
        /**
         * PropertyInterest
         * @enum {string}
         */
        PropertyInterest: "new" | "second_hand" | "both";
        /** PropertyList */
        PropertyList: {
            /** Items */
            items: components["schemas"]["PropertyListItem"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** PropertyListItem */
        PropertyListItem: {
            /** Address */
            address: string;
            confidence: components["schemas"]["GeocodeConfidence"];
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            latestSale: components["schemas"]["LatestSale"];
            /** Lng */
            lng: number;
            /** Nsales */
            nSales: number;
        };
        /** PropertySummary */
        PropertySummary: {
            /** Address */
            address: string;
            area?: components["schemas"]["AreaLine"] | null;
            confidence: components["schemas"]["GeocodeConfidence"];
            /** Dataversion */
            dataVersion: string;
            /** Id */
            id: string;
            latestSale?: components["schemas"]["LatestSale"] | null;
            /** Previoussales */
            previousSales?: components["schemas"]["SaleBrief"][];
            vicinity: components["schemas"]["Vicinity"];
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Acceptterms
             * @constant
             */
            acceptTerms: true;
            /**
             * Age18Plus
             * @constant
             */
            age18Plus: true;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Fullname */
            fullName: string;
            /**
             * Marketingoptin
             * @default false
             */
            marketingOptIn: boolean;
            /** Password */
            password: string;
            /** Privacyversion */
            privacyVersion: string;
            profile?: components["schemas"]["Profile-Input"] | null;
            /** Termsversion */
            termsVersion: string;
        };
        /** ResetIn */
        ResetIn: {
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /** Sale */
        Sale: {
            /** Bulkgroupsize */
            bulkGroupSize: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Isnew */
            isNew: boolean;
            /** Notfullmarketprice */
            notFullMarketPrice: boolean;
            /** Possibleduplicate */
            possibleDuplicate: boolean;
            /** Priceeur */
            priceEur: number;
            /** Sizeband */
            sizeBand: string | null;
            /** Vatexclusive */
            vatExclusive: boolean;
        };
        /** SaleBrief */
        SaleBrief: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Priceeur */
            priceEur: number;
        };
        /** SaleFlags */
        SaleFlags: {
            /** Bulk */
            bulk: boolean;
            /** Notfullmarketprice */
            notFullMarketPrice: boolean;
            /** Vatexclusive */
            vatExclusive: boolean;
        };
        /** SchoolValue */
        SchoolValue: {
            /** Distancem */
            distanceM: number;
            /** Name */
            name?: string | null;
        };
        /** Sourced[SchoolValue] */
        Sourced_SchoolValue_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            value: components["schemas"]["SchoolValue"];
        };
        /** Sourced[StopValue] */
        Sourced_StopValue_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            value: components["schemas"]["StopValue"];
        };
        /** Sourced[int] */
        Sourced_int_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            /** Value */
            value: number;
        };
        /** Sourced[str] */
        Sourced_str_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            /** Value */
            value: string;
        };
        /** StatsPoint */
        StatsPoint: {
            /** Median */
            median: number | null;
            /** N */
            n: number;
            /**
             * Periodstart
             * Format: date
             */
            periodStart: string;
            /** Provisional */
            provisional: boolean;
            /** Suppressed */
            suppressed: boolean;
        };
        /** StopValue */
        StopValue: {
            /** Distancem */
            distanceM: number;
            /** Name */
            name?: string | null;
            type: components["schemas"]["PoiType"];
        };
        /** TokenIn */
        TokenIn: {
            /** Token */
            token: string;
        };
        /**
         * UserType
         * @enum {string}
         */
        UserType: "first_time_buyer" | "mover" | "investor" | "agent" | "researcher";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vicinity */
        Vicinity: {
            deprivation?: components["schemas"]["Sourced_str_"] | null;
            /** Distances */
            distances?: "straight line" | null;
            flood: components["schemas"]["Flood"];
            nearestPostPrimarySchool?: components["schemas"]["Sourced_SchoolValue_"] | null;
            nearestPrimarySchool?: components["schemas"]["Sourced_SchoolValue_"] | null;
            nearestStop?: components["schemas"]["Sourced_StopValue_"] | null;
            shopsWithin1km?: components["schemas"]["Sourced_int_"] | null;
        };
        /** ViewIn */
        ViewIn: {
            /** Propertyid */
            propertyId: string;
        };
        /** ViewOut */
        ViewOut: {
            /** Address */
            address: string;
            /** Id */
            id: number;
            /** Propertyid */
            propertyId: string;
            /**
             * Viewedat
             * Format: date-time
             */
            viewedAt: string;
        };
        /** WishlistIn */
        WishlistIn: {
            /** Areaslug */
            areaSlug?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Propertyid
             * @description The property's public id
             */
            propertyId?: string | null;
        };
        /** WishlistItemOut */
        WishlistItemOut: {
            /** Areaslug */
            areaSlug: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Latestpriceeur */
            latestPriceEur?: number | null;
            /** Latestsaledate */
            latestSaleDate?: string | null;
            /** Note */
            note: string | null;
            /** Propertyid */
            propertyId: string | null;
            /** Title */
            title: string;
        };
        /** WishlistNote */
        WishlistNote: {
            /** Note */
            note?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    policies_api_v1_auth_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policies"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    delete_me_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_me_api_v1_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    views_api_v1_me_history_views_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewOut"][];
                };
            };
        };
    };
    record_view_api_v1_me_history_views_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_views_api_v1_me_history_views_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_view_api_v1_me_history_views__view_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wishlist_api_v1_me_wishlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemOut"][];
                };
            };
        };
    };
    add_to_wishlist_api_v1_me_wishlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistIn"];
            };
        };
        responses: {
            /** @description Already saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemOut"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_me_wishlist_compare_get: {
        parameters: {
            query: {
                /** @description Up to 4 property ids from the wishlist, comma-separated */
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_wishlist_item_api_v1_me_wishlist__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    note_wishlist_item_api_v1_me_wishlist__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistNote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    list_properties_api_v1_properties_get: {
        parameters: {
            query: {
                /** @description west,south,east,north in degrees */
                bbox: string;
                sort?: "-date" | "date" | "-price" | "price";
                page?: number;
                pageSize?: number;
                priceMin?: number | string | null;
                priceMax?: number | string | null;
                dateFrom?: string | null;
                dateTo?: string | null;
                type?: "new" | "second_hand" | "any";
                excludeNonMarket?: boolean;
                excludeBulk?: boolean;
                minConfidence?: components["schemas"]["GeocodeConfidence"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyList"];
                };
            };
            /** @description The box is too large: zoom in */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    property_detail_api_v1_properties__property_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_properties__property_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_stats_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
}
