/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/areas/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Area Detail
         * @description An area with its parents, shape, latest complete 12 months against Ireland's, what is
         *     known about it, and its busiest sub-areas.
         */
        get: operations["area_detail_api_v1_areas__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/areas/{slug}/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Distribution
         * @description How many market sales fell in each price band over the latest complete 12 months, with
         *     Ireland's shares for comparison. Bands with fewer than 5 sales are not given.
         */
        get: operations["distribution_api_v1_areas__slug__distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/areas/{slug}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Area Stats
         * @description The area's series from `area_stats`, with Ireland's for the same periods. Periods with
         *     fewer than 5 sales keep their count and have no prices; the latest two months are
         *     provisional. Small Areas and townlands have quarters and years only.
         */
        get: operations["area_stats_api_v1_areas__slug__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Sign out. Succeeds, and clears the cookie, even if the session had already ended.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout All */
        post: operations["logout_all_api_v1_auth_logout_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Policies
         * @description The versions of the terms and privacy policy that registration accepts.
         */
        get: operations["policies_api_v1_auth_policies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create an account and email a verification link. Always 202.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_api_v1_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/geocode/autocomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Autocomplete
         * @description Places and addresses we hold data for (D-006): counties, towns, Electoral Divisions,
         *     townlands, Eircode routing keys (and Dublin postal districts), and property addresses.
         *     Nothing is sent to a third party.
         */
        get: operations["autocomplete_api_v1_geocode_autocomplete_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness and dependency check: database and Redis.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Close the account now; its data is purged after 30 days (`app.cli purge-deleted`).
         */
        delete: operations["delete_me_api_v1_me_delete"];
        options?: never;
        head?: never;
        /** Patch Me */
        patch: operations["patch_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Me
         * @description Everything stored about the account, as a JSON download (GDPR access request).
         */
        get: operations["export_me_api_v1_me_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/history/searches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Searches */
        get: operations["searches_api_v1_me_history_searches_get"];
        put?: never;
        /**
         * Record Search
         * @description Keep a search the user ran, unless history is off. Running the same search again
         *     moves it to the top instead of adding a copy.
         */
        post: operations["record_search_api_v1_me_history_searches_post"];
        /** Clear Searches */
        delete: operations["clear_searches_api_v1_me_history_searches_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/history/searches/{search_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Search */
        delete: operations["delete_search_api_v1_me_history_searches__search_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/history/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Views
         * @description Property pages visited in the last 12 months, newest first.
         */
        get: operations["views_api_v1_me_history_views_get"];
        put?: never;
        /**
         * Record View
         * @description Record a property page visit, unless history is switched off (then nothing is kept).
         */
        post: operations["record_view_api_v1_me_history_views_post"];
        /** Clear Views */
        delete: operations["clear_views_api_v1_me_history_views_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/history/views/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete View */
        delete: operations["delete_view_api_v1_me_history_views__view_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Change the password; every other session is signed out and reset links stop working.
         */
        post: operations["change_password_api_v1_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wishlist */
        get: operations["wishlist_api_v1_me_wishlist_get"];
        put?: never;
        /**
         * Add To Wishlist
         * @description Save a property or an area (201). Saving the same one again returns the existing item
         *     (200), with its note replaced if a new one is given.
         */
        post: operations["add_to_wishlist_api_v1_me_wishlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wishlist/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Compare
         * @description Side by side: the hover summaries of up to four saved properties, in the order given.
         */
        get: operations["compare_api_v1_me_wishlist_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wishlist/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Wishlist Item */
        delete: operations["remove_wishlist_item_api_v1_me_wishlist__item_id__delete"];
        options?: never;
        head?: never;
        /** Note Wishlist Item */
        patch: operations["note_wishlist_item_api_v1_me_wishlist__item_id__patch"];
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Meta
         * @description Data freshness for the banner: the latest sale in the register and what is provisional.
         */
        get: operations["meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Properties
         * @description The list view synced with the map: the latest matching sale per property in the box.
         *     It is /search limited to the box, so it takes the same filters.
         */
        get: operations["list_properties_api_v1_properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Property Detail
         * @description The property page: every sale, location precision, areas, vicinity and area trend.
         */
        get: operations["property_detail_api_v1_properties__property_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Summary
         * @description The hover card: one precomputed row, cached in Redis per data version.
         */
        get: operations["summary_api_v1_properties__property_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Every property whose latest matching sale passes the filters: the same matches as the
         *     map (`/tiles/sales` takes the same parameters). `-change` sorts by the largest rise since
         *     the previous plain market sale.
         */
        get: operations["search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Sales per month nationally, and each county's latest complete 12 months.
         */
        get: operations["overview_api_v1_stats_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/affordability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Affordability
         * @description The most the Central Bank measures allow you to borrow and spend: the lower of the
         *     income limit and the deposit limit. Lenders may lend less.
         */
        get: operations["affordability_api_v1_tools_affordability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rules
         * @description Which rules the calculators use, their sources and when they were checked.
         */
        get: operations["rules_api_v1_tools_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tools/stamp-duty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stamp Duty
         * @description Stamp duty on one home at today's rates. On a new home it is charged on the price
         *     without VAT.
         */
        get: operations["stamp_duty_api_v1_tools_stamp_duty_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Accepted
         * @description 202 answers never say whether an account exists.
         */
        Accepted: {
            /** Message */
            message: string;
            /**
             * Status
             * @default accepted
             * @constant
             */
            status: "accepted";
        };
        /** AffordabilityOut */
        AffordabilityOut: {
            /** Allowance */
            allowance: number;
            /** Depositeur */
            depositEur: number;
            /** Incomeeur */
            incomeEur: number;
            /**
             * Limitedby
             * @enum {string}
             */
            limitedBy: "income" | "deposit";
            /** Loaneur */
            loanEur: number;
            /** Loantoincome */
            loanToIncome: number | null;
            /** Loantovalue */
            loanToValue: number;
            /** Maxloanbyincomeeur */
            maxLoanByIncomeEur: number | null;
            /** Maxpricebydepositeur */
            maxPriceByDepositEur: number;
            /** Maxpriceeur */
            maxPriceEur: number;
            /** Measuresnote */
            measuresNote: string;
            /** Monthlyrepaymenteur */
            monthlyRepaymentEur: number | null;
            /**
             * Note
             * @default Information only, not financial or tax advice. Lenders decide individually, and your own circumstances or reliefs may change the figures.
             */
            note: string;
            /** Rulesversion */
            rulesVersion: string;
            /** Sources */
            sources: components["schemas"]["Source"][];
            /** Stampdutyeur */
            stampDutyEur: number;
        };
        /** AreaAttributeOut */
        AreaAttributeOut: {
            /**
             * Asof
             * Format: date
             */
            asOf: string;
            /** Label */
            label: string;
            /** Licence */
            licence: string;
            /** Source */
            source: string;
            /** Value */
            value: string;
        };
        /** AreaDetail */
        AreaDetail: {
            /** Attributes */
            attributes: components["schemas"]["AreaAttributeOut"][];
            /** Bbox */
            bbox: number[];
            /** Children */
            children: components["schemas"]["SubArea"][];
            /** Childrenkind */
            childrenKind: string | null;
            /** Code */
            code: string;
            /** Dataversion */
            dataVersion: string;
            /**
             * Geometry
             * @description Simplified GeoJSON, for display only
             */
            geometry: {
                [key: string]: unknown;
            };
            headline: components["schemas"]["Headline"] | null;
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Namega */
            nameGa: string | null;
            national: components["schemas"]["Headline"] | null;
            /** Parents */
            parents: components["schemas"]["AreaRef"][];
            /**
             * Periodkinds
             * @description Series this area has
             */
            periodKinds: ("month" | "quarter" | "year" | "rolling_12m")[];
            /**
             * Pointbased
             * @description True for Small Areas and EDs: only sales placed at their house or street can be counted in them
             */
            pointBased: boolean;
            /** Slug */
            slug: string;
            /** Source */
            source: string;
        };
        /** AreaLine */
        AreaLine: {
            /** Change12Mpct */
            change12mPct?: number | null;
            /** Kind */
            kind: string;
            /** Median12M */
            median12m?: number | null;
            /** N */
            n: number;
            /** Name */
            name: string;
            /** Provisional */
            provisional: boolean;
        };
        /** AreaRef */
        AreaRef: {
            /** Kind */
            kind: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** AreaSeries */
        AreaSeries: {
            area: components["schemas"]["AreaRef"];
            /**
             * Periodkind
             * @default rolling_12m
             * @constant
             */
            periodKind: "rolling_12m";
            /** Points */
            points: components["schemas"]["StatsPoint"][];
        };
        /** AreaStatsOut */
        AreaStatsOut: {
            area: components["schemas"]["AreaRef"];
            /**
             * National
             * @description Ireland, same periods and segment
             */
            national: components["schemas"]["SeriesPoint"][];
            /**
             * Periodkind
             * @enum {string}
             */
            periodKind: "month" | "quarter" | "year" | "rolling_12m";
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
            /**
             * Segment
             * @enum {string}
             */
            segment: "all" | "new" | "second_hand";
        };
        /** Bin */
        Bin: {
            /** Fromeur */
            fromEur: number;
            /**
             * N
             * @description null when fewer than 5 sales (suppressed)
             */
            n: number | null;
            /** Toeur */
            toEur: number | null;
        };
        /**
         * County
         * @enum {string}
         */
        County: "carlow" | "cavan" | "clare" | "cork" | "donegal" | "dublin" | "galway" | "kerry" | "kildare" | "kilkenny" | "laois" | "leitrim" | "limerick" | "longford" | "louth" | "mayo" | "meath" | "monaghan" | "offaly" | "roscommon" | "sligo" | "tipperary" | "waterford" | "westmeath" | "wexford" | "wicklow";
        /** CountyStat */
        CountyStat: {
            /**
             * Lat
             * @description A point inside the county, for centring the map.
             */
            lat: number;
            /** Lng */
            lng: number;
            /**
             * Medianpriceeur
             * @description None when fewer than 5 sales.
             */
            medianPriceEur: number | null;
            /** Name */
            name: string;
            /**
             * Sales
             * @description Market sales in the 12 months to `Overview.windowEnd`.
             */
            sales: number;
            /** Slug */
            slug: string;
        };
        /** Distribution */
        Distribution: {
            area: components["schemas"]["AreaRef"];
            /** Bins */
            bins: components["schemas"]["Bin"][];
            /** N */
            n: number;
            /**
             * Nationalshare
             * @description Share of Ireland's sales in each bin, for comparison
             */
            nationalShare: (number | null)[];
            /**
             * Windowend
             * Format: date
             */
            windowEnd: string;
            /**
             * Windowstart
             * Format: date
             */
            windowStart: string;
        };
        /** DutyBandOut */
        DutyBandOut: {
            /** Dutyeur */
            dutyEur: number;
            /** Fromeur */
            fromEur: number;
            /** Rate */
            rate: number;
            /** Toeur */
            toEur: number | null;
        };
        /** EmailIn */
        EmailIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** Flood */
        Flood: {
            /** Link */
            link: string;
            /** Note */
            note: string;
        };
        /**
         * GeocodeConfidence
         * @description Ordered from most to least precise (D-003).
         * @enum {string}
         */
        GeocodeConfidence: "exact" | "street" | "locality" | "routing_key" | "county" | "unmatched";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Headline
         * @description The latest complete 12 months (no provisional month in it).
         */
        Headline: {
            /**
             * Changepct
             * @description Median against the 12 months a year earlier; null if either is suppressed
             */
            changePct?: number | null;
            /** Median */
            median: number | null;
            /** N */
            n: number;
            /** P25 */
            p25: number | null;
            /** P75 */
            p75: number | null;
            /**
             * Windowend
             * Format: date
             */
            windowEnd: string;
            /**
             * Windowstart
             * Format: date
             */
            windowStart: string;
        };
        /** Health */
        Health: {
            /**
             * Database
             * @enum {string}
             */
            database: "ok" | "error";
            /**
             * Redis
             * @enum {string}
             */
            redis: "ok" | "error";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
        };
        /** LatestSale */
        LatestSale: {
            /**
             * Date
             * Format: date
             */
            date: string;
            flags: components["schemas"]["SaleFlags"];
            /** Isnew */
            isNew: boolean;
            /** Priceeur */
            priceEur: number;
        };
        /** Location */
        Location: {
            confidence: components["schemas"]["GeocodeConfidence"];
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Method */
            method: string | null;
            /** Source */
            source: string | null;
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Me */
        Me: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Email */
            email: string;
            /** Emailverified */
            emailVerified: boolean;
            /** Fullname */
            fullName: string;
            /** Historyenabled */
            historyEnabled: boolean;
            /** Id */
            id: string;
            /** Marketingoptin */
            marketingOptIn: boolean;
            /** Permissions */
            permissions: string[];
            profile: components["schemas"]["Profile-Output"];
            /** Roles */
            roles: string[];
        };
        /**
         * MePatch
         * @description Only the fields sent are changed; within `profile`, too.
         */
        MePatch: {
            /** Fullname */
            fullName?: string | null;
            /** Historyenabled */
            historyEnabled?: boolean | null;
            /** Marketingoptin */
            marketingOptIn?: boolean | null;
            profile?: components["schemas"]["Profile-Input"] | null;
        };
        /** Meta */
        Meta: {
            /** Dataversion */
            dataVersion: string;
            /** Lastingestat */
            lastIngestAt: string | null;
            /**
             * Pprmaxsaledate
             * Format: date
             */
            pprMaxSaleDate: string;
            /**
             * Provisionalfrom
             * Format: date
             * @description Sales on or after this date are provisional.
             */
            provisionalFrom: string;
        };
        /** MonthCount */
        MonthCount: {
            /**
             * Month
             * Format: date
             * @description First day of the month.
             */
            month: string;
            /**
             * Provisional
             * @description Late filings still arrive for this month.
             */
            provisional: boolean;
            /**
             * Sales
             * @description Market sales filed for this month, all counties.
             */
            sales: number;
        };
        /** Overview */
        Overview: {
            /**
             * Counties
             * @description Most sales first.
             */
            counties: components["schemas"]["CountyStat"][];
            /** Dataversion */
            dataVersion: string;
            /**
             * Firstsaledate
             * Format: date
             */
            firstSaleDate: string;
            /**
             * Monthly
             * @description The last 24 months, oldest first.
             */
            monthly: components["schemas"]["MonthCount"][];
            /** Totalproperties */
            totalProperties: number;
            /**
             * Totalsales
             * @description Every sale on the register, market or not.
             */
            totalSales: number;
            /**
             * Windowend
             * Format: date
             * @description Last month of that window: the latest complete one.
             */
            windowEnd: string;
            /**
             * Windowstart
             * Format: date
             * @description First month of the counties' 12-month window.
             */
            windowStart: string;
        };
        /** Page[SearchHistoryOut] */
        Page_SearchHistoryOut_: {
            /** Items */
            items: components["schemas"]["SearchHistoryOut"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** Page[ViewOut] */
        Page_ViewOut_: {
            /** Items */
            items: components["schemas"]["ViewOut"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** PasswordChangeIn */
        PasswordChangeIn: {
            /** Currentpassword */
            currentPassword: string;
            /** Newpassword */
            newPassword: string;
        };
        /** PasswordIn */
        PasswordIn: {
            /** Password */
            password: string;
        };
        /**
         * PoiType
         * @enum {string}
         */
        PoiType: "school_primary" | "school_post_primary" | "school_special" | "bus_stop" | "luas_stop" | "rail_station" | "dart_station" | "shop" | "supermarket" | "pharmacy" | "park" | "gym" | "restaurant" | "gp";
        /** Policies */
        Policies: {
            /** Privacyversion */
            privacyVersion: string;
            /** Termsversion */
            termsVersion: string;
        };
        /**
         * PriceChange
         * @description Against the previous sale, only when both are plain market sales; not adjusted for
         *     inflation or for work done in between.
         */
        PriceChange: {
            /** Changepct */
            changePct: number;
            /**
             * Previousdate
             * Format: date
             */
            previousDate: string;
            /** Previouspriceeur */
            previousPriceEur: number;
        };
        /** Profile */
        "Profile-Input": {
            /** Budgetmax */
            budgetMax?: number | string | null;
            /** Budgetmin */
            budgetMin?: number | string | null;
            /** Counties */
            counties?: components["schemas"]["County"][] | null;
            propertyInterest?: components["schemas"]["PropertyInterest"] | null;
            userType?: components["schemas"]["UserType"] | null;
        };
        /** Profile */
        "Profile-Output": {
            /** Budgetmax */
            budgetMax?: number | null;
            /** Budgetmin */
            budgetMin?: number | null;
            /** Counties */
            counties?: components["schemas"]["County"][] | null;
            propertyInterest?: components["schemas"]["PropertyInterest"] | null;
            userType?: components["schemas"]["UserType"] | null;
        };
        /** PropertyDetail */
        PropertyDetail: {
            /** Address */
            address: string;
            areaSeries: components["schemas"]["AreaSeries"] | null;
            /** Areas */
            areas: components["schemas"]["AreaRef"][];
            /** Caveats */
            caveats: string[];
            /** County */
            county: string;
            /** Dataversion */
            dataVersion: string;
            /** Dublindistrict */
            dublinDistrict: string | null;
            /** Id */
            id: string;
            location: components["schemas"]["Location"];
            /** Routingkey */
            routingKey: string | null;
            /** Sales */
            sales: components["schemas"]["Sale"][];
            vicinity: components["schemas"]["Vicinity"];
        };
        /**
         * PropertyInterest
         * @enum {string}
         */
        PropertyInterest: "new" | "second_hand" | "both";
        /** PropertyList */
        PropertyList: {
            /** Items */
            items: components["schemas"]["PropertyListItem"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Total */
            total: number;
        };
        /** PropertyListItem */
        PropertyListItem: {
            /** Address */
            address: string;
            change?: components["schemas"]["PriceChange"] | null;
            confidence: components["schemas"]["GeocodeConfidence"];
            /** Id */
            id: string;
            /** Lat */
            lat: number;
            latestSale: components["schemas"]["LatestSale"];
            /** Lng */
            lng: number;
            /** Nsales */
            nSales: number;
        };
        /** PropertySummary */
        PropertySummary: {
            /** Address */
            address: string;
            area?: components["schemas"]["AreaLine"] | null;
            confidence: components["schemas"]["GeocodeConfidence"];
            /** Dataversion */
            dataVersion: string;
            /** Id */
            id: string;
            latestSale?: components["schemas"]["LatestSale"] | null;
            /** Previoussales */
            previousSales?: components["schemas"]["SaleBrief"][];
            vicinity: components["schemas"]["Vicinity"];
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Acceptterms
             * @constant
             */
            acceptTerms: true;
            /**
             * Age18Plus
             * @constant
             */
            age18Plus: true;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Fullname */
            fullName: string;
            /**
             * Marketingoptin
             * @default false
             */
            marketingOptIn: boolean;
            /** Password */
            password: string;
            /** Privacyversion */
            privacyVersion: string;
            profile?: components["schemas"]["Profile-Input"] | null;
            /** Termsversion */
            termsVersion: string;
        };
        /** ResetIn */
        ResetIn: {
            /** Password */
            password: string;
            /** Token */
            token: string;
        };
        /** Rules */
        Rules: {
            /**
             * Note
             * @default Information only, not financial or tax advice. Lenders decide individually, and your own circumstances or reliefs may change the figures.
             */
            note: string;
            /** Rulesversion */
            rulesVersion: string;
            /** Sources */
            sources: components["schemas"]["Source"][];
        };
        /** Sale */
        Sale: {
            /** Bulkgroupsize */
            bulkGroupSize: number | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Isnew */
            isNew: boolean;
            /** Notfullmarketprice */
            notFullMarketPrice: boolean;
            /** Possibleduplicate */
            possibleDuplicate: boolean;
            /** Priceeur */
            priceEur: number;
            /** Sizeband */
            sizeBand: string | null;
            /** Vatestimates */
            vatEstimates?: components["schemas"]["VatEstimate"][];
            /** Vatexclusive */
            vatExclusive: boolean;
        };
        /** SaleBrief */
        SaleBrief: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Priceeur */
            priceEur: number;
        };
        /** SaleFlags */
        SaleFlags: {
            /** Bulk */
            bulk: boolean;
            /** Notfullmarketprice */
            notFullMarketPrice: boolean;
            /** Vatexclusive */
            vatExclusive: boolean;
        };
        /** SchoolValue */
        SchoolValue: {
            /** Distancem */
            distanceM: number;
            /** Name */
            name?: string | null;
        };
        /** SearchHistoryIn */
        SearchHistoryIn: {
            /**
             * Label
             * @description What the user searched for
             */
            label?: string | null;
            /**
             * Query
             * @description The search's URL parameters
             */
            query: {
                [key: string]: string;
            };
        };
        /** SearchHistoryOut */
        SearchHistoryOut: {
            /** Id */
            id: number;
            /** Label */
            label: string | null;
            /** Query */
            query: {
                [key: string]: string;
            };
            /**
             * Searchedat
             * Format: date-time
             */
            searchedAt: string;
        };
        /** SearchResults */
        SearchResults: {
            /**
             * Bbox
             * @description west, south, east, north of every match; null when none match
             */
            bbox?: number[] | null;
            /** Items */
            items: components["schemas"]["PropertyListItem"][];
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /**
             * Places
             * @description The areas named by the `area` filter
             */
            places?: components["schemas"]["AreaRef"][];
            /**
             * Query
             * @description The filters applied, as URL parameters
             */
            query: {
                [key: string]: string;
            };
            /** Total */
            total: number;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /** Median */
            median: number | null;
            /** N */
            n: number;
            /** P25 */
            p25: number | null;
            /** P75 */
            p75: number | null;
            /**
             * Periodstart
             * Format: date
             */
            periodStart: string;
            /** Provisional */
            provisional: boolean;
            /** Suppressed */
            suppressed: boolean;
        };
        /** Source */
        Source: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Verifiedon
             * Format: date
             */
            verifiedOn: string;
        };
        /** Sourced[SchoolValue] */
        Sourced_SchoolValue_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            value: components["schemas"]["SchoolValue"];
        };
        /** Sourced[StopValue] */
        Sourced_StopValue_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            value: components["schemas"]["StopValue"];
        };
        /** Sourced[int] */
        Sourced_int_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            /** Value */
            value: number;
        };
        /** Sourced[str] */
        Sourced_str_: {
            /** Asof */
            asOf?: string | null;
            /** Source */
            source: string;
            /** Value */
            value: string;
        };
        /** StampDutyOut */
        StampDutyOut: {
            /** Bands */
            bands: components["schemas"]["DutyBandOut"][];
            /** Considerationeur */
            considerationEur: number;
            /** Dutyeur */
            dutyEur: number;
            /** Effectiverate */
            effectiveRate: number;
            /** Notcovered */
            notCovered: string;
            /**
             * Note
             * @default Information only, not financial or tax advice. Lenders decide individually, and your own circumstances or reliefs may change the figures.
             */
            note: string;
            /** Priceeur */
            priceEur: number;
            /** Rulesversion */
            rulesVersion: string;
            /** Sources */
            sources: components["schemas"]["Source"][];
            /** Vateur */
            vatEur: number;
            /** Vatrate */
            vatRate: number | null;
        };
        /** StatsPoint */
        StatsPoint: {
            /** Median */
            median: number | null;
            /** N */
            n: number;
            /**
             * Periodstart
             * Format: date
             */
            periodStart: string;
            /** Provisional */
            provisional: boolean;
            /** Suppressed */
            suppressed: boolean;
        };
        /** StopValue */
        StopValue: {
            /** Distancem */
            distanceM: number;
            /** Name */
            name?: string | null;
            type: components["schemas"]["PoiType"];
        };
        /** SubArea */
        SubArea: {
            /** Kind */
            kind: string;
            /** Median */
            median: number | null;
            /** N */
            n: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /**
         * Suggestion
         * @description One autocomplete answer: a place to filter by, or a property to open.
         */
        Suggestion: {
            /** Bbox */
            bbox?: number[] | null;
            /** Detail */
            detail?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "county" | "settlement" | "electoral_division" | "townland" | "routing_key" | "property";
            /** Label */
            label: string;
            /** Lat */
            lat?: number | null;
            /** Lng */
            lng?: number | null;
            /** Propertyid */
            propertyId?: string | null;
            /** Routingkey */
            routingKey?: string | null;
            /**
             * Slug
             * @description Area slug, for area kinds
             */
            slug?: string | null;
        };
        /** TokenIn */
        TokenIn: {
            /** Token */
            token: string;
        };
        /**
         * UserType
         * @enum {string}
         */
        UserType: "first_time_buyer" | "mover" | "investor" | "agent" | "researcher";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VatEstimate
         * @description A VAT-exclusive price with VAT added: an estimate, never the price paid (D-015).
         */
        VatEstimate: {
            /**
             * Appliesto
             * @description 'any' new dwelling, or only a qualifying apartment (9% from 8 Oct 2025)
             * @enum {string}
             */
            appliesTo: "any" | "qualifying_apartment";
            /** Priceeur */
            priceEur: number;
            /** Rate */
            rate: number;
        };
        /** Vicinity */
        Vicinity: {
            deprivation?: components["schemas"]["Sourced_str_"] | null;
            /** Distances */
            distances?: "straight line" | null;
            flood: components["schemas"]["Flood"];
            nearestPostPrimarySchool?: components["schemas"]["Sourced_SchoolValue_"] | null;
            nearestPrimarySchool?: components["schemas"]["Sourced_SchoolValue_"] | null;
            nearestStop?: components["schemas"]["Sourced_StopValue_"] | null;
            shopsWithin1km?: components["schemas"]["Sourced_int_"] | null;
        };
        /** ViewIn */
        ViewIn: {
            /** Propertyid */
            propertyId: string;
        };
        /** ViewOut */
        ViewOut: {
            /** Address */
            address: string;
            /** Id */
            id: number;
            /** Propertyid */
            propertyId: string;
            /**
             * Viewedat
             * Format: date-time
             */
            viewedAt: string;
        };
        /** WishlistIn */
        WishlistIn: {
            /** Areaslug */
            areaSlug?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Propertyid
             * @description The property's public id
             */
            propertyId?: string | null;
        };
        /** WishlistItemOut */
        WishlistItemOut: {
            /** Areaslug */
            areaSlug: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Latestpriceeur */
            latestPriceEur?: number | null;
            /** Latestsaledate */
            latestSaleDate?: string | null;
            /** Note */
            note: string | null;
            /** Propertyid */
            propertyId: string | null;
            /** Title */
            title: string;
        };
        /** WishlistNote */
        WishlistNote: {
            /** Note */
            note?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    area_detail_api_v1_areas__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    distribution_api_v1_areas__slug__distribution_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Distribution"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    area_stats_api_v1_areas__slug__stats_get: {
        parameters: {
            query?: {
                periodKind?: ("month" | "quarter" | "year" | "rolling_12m") | null;
                segment?: "all" | "new" | "second_hand";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaStatsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout_all_api_v1_auth_logout_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    policies_api_v1_auth_policies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Policies"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Accepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autocomplete_api_v1_geocode_autocomplete_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    delete_me_api_v1_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_me_api_v1_me_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    searches_api_v1_me_history_searches_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SearchHistoryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_search_api_v1_me_history_searches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchHistoryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_searches_api_v1_me_history_searches_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_search_api_v1_me_history_searches__search_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                search_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    views_api_v1_me_history_views_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ViewOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_view_api_v1_me_history_views_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_views_api_v1_me_history_views_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_view_api_v1_me_history_views__view_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordChangeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wishlist_api_v1_me_wishlist_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemOut"][];
                };
            };
        };
    };
    add_to_wishlist_api_v1_me_wishlist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistIn"];
            };
        };
        responses: {
            /** @description Already saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemOut"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_api_v1_me_wishlist_compare_get: {
        parameters: {
            query: {
                /** @description Up to 4 property ids from the wishlist, comma-separated */
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_wishlist_item_api_v1_me_wishlist__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    note_wishlist_item_api_v1_me_wishlist__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistNote"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WishlistItemOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    list_properties_api_v1_properties_get: {
        parameters: {
            query: {
                /** @description west,south,east,north in degrees */
                bbox: string;
                sort?: "-date" | "date" | "-price" | "price" | "-change" | "change";
                page?: number;
                pageSize?: number;
                priceMin?: number | string | null;
                priceMax?: number | string | null;
                dateFrom?: string | null;
                dateTo?: string | null;
                type?: "new" | "second_hand" | "any";
                excludeNonMarket?: boolean;
                excludeBulk?: boolean;
                minConfidence?: components["schemas"]["GeocodeConfidence"];
                vat?: "exclusive" | "inclusive" | "any";
                /** @description Counties, comma-separated */
                county?: string | null;
                /** @description Area slugs, comma-separated */
                area?: string | null;
                /** @description Eircode routing keys, e.g. D08,A63 */
                routingKey?: string | null;
                /** @description lat,lng */
                near?: string | null;
                /** @description With near; 100 to 20,000, default 1,000 */
                radiusM?: number | null;
                /** @description Nearest stop within this many metres */
                maxStopM?: number | null;
                /** @description Nearest school within this many metres */
                maxSchoolM?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyList"];
                };
            };
            /** @description The box is too large: zoom in */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    property_detail_api_v1_properties__property_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_api_v1_properties__property_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_v1_search_get: {
        parameters: {
            query?: {
                /** @description west,south,east,north */
                bbox?: string | null;
                sort?: "-date" | "date" | "-price" | "price" | "-change" | "change";
                page?: number;
                pageSize?: number;
                priceMin?: number | string | null;
                priceMax?: number | string | null;
                dateFrom?: string | null;
                dateTo?: string | null;
                type?: "new" | "second_hand" | "any";
                excludeNonMarket?: boolean;
                excludeBulk?: boolean;
                minConfidence?: components["schemas"]["GeocodeConfidence"];
                vat?: "exclusive" | "inclusive" | "any";
                /** @description Counties, comma-separated */
                county?: string | null;
                /** @description Area slugs, comma-separated */
                area?: string | null;
                /** @description Eircode routing keys, e.g. D08,A63 */
                routingKey?: string | null;
                /** @description lat,lng */
                near?: string | null;
                /** @description With near; 100 to 20,000, default 1,000 */
                radiusM?: number | null;
                /** @description Nearest stop within this many metres */
                maxStopM?: number | null;
                /** @description Nearest school within this many metres */
                maxSchoolM?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResults"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_v1_stats_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    affordability_api_v1_tools_affordability_get: {
        parameters: {
            query: {
                grossIncome: number | string;
                deposit: number | string;
                secondIncome?: number | string;
                buyer?: "first_time_buyer" | "second_and_subsequent" | "buy_to_let";
                /** @description Shorthand for buyer */
                firstTimeBuyer?: boolean | null;
                termYears?: number;
                /** @description Your quoted rate */
                ratePct?: number | string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AffordabilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rules_api_v1_tools_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rules"];
                };
            };
        };
    };
    stamp_duty_api_v1_tools_stamp_duty_get: {
        parameters: {
            query: {
                /** @description Price in euro */
                price: number | string;
                isNew?: boolean;
                /** @description For a new home: the price includes VAT */
                vatInclusive?: boolean;
                /** @description A new apartment in a block of 3+ with shared access (9% VAT since 8 Oct 2025) */
                qualifyingApartment?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StampDutyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
